# Generated by Django 5.0.4 on 2026-04-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_order_user_order_address_order_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
